### ISSUE TITLE
Is there a way to cache apt-get installs?

### ISSUE THREAD

**Issue by dashmug** [aws-samples/aws-codebuild-samples#7]
It would be nice if CodeBuild can. Most of the time, OS package installation takes a long time.

**Comment by subinataws** [comment]
@dashmug - There is no native support for that. It is likely easier to use a custom Docker image with the packages that you need pre-installed on them.

**Comment by dashmug** [comment]
Right. That's what I'm currently doing. Thanks.

**Comment by diegocarrillo** [comment]
is there still no option to caché the update of codebuild images?
